### ISSUE TITLE
What effect does this have on the extracted features setting the sampling rate to 22050?

### ISSUE THREAD

**Issue by FriedaSmith** [ShaheenPerveen/speech-emotion-recognition-iemocap#1]
Hello. IEMOCAP native sample rate is **16k**. However, you set the sampling rate to 22050 in repository(**sr = 22050**). What effect does this have on the extracted features?

**Comment by ShaheenPerveen** [comment]
hi @FriedaSmith 
The extracted features/spectrogram were more granular at this sampling rate as you are drawing more samples in a given time interval. You can try plotting spectrograms at different sampling rate and compare

**Comment by ShaheenPerveen** [comment]
Let me know if the above comment did not resolve your issue. Closing it for now
