### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by Lanther1** [ShaheenPerveen/speech-emotion-recognition-iemocap#2]
AttributeError: Can't get attribute 'save_spectrogram' on <module '__main__' (built-in)>

step:     saving_spectrogram_audio_data_parallel  (def save_spectrogram(y, image_fname, label):)

I have no ideas to deal with this issues.I have searched fo a long time to find  the solutions，but all of them did not work.
 I use win10+python3.8.12 .And the requrements are as followed.
appdirs             1.4.4
argon2-cffi         20.1.0
async-generator     1.10
attrs               21.2.0
audioread           2.1.9
backcall            0.2.0
bleach              4.0.0
certifi             2021.10.8
cffi                1.15.0
charset-normalizer  2.0.9
colorama            0.4.4
cycler              0.11.0
debugpy             1.5.1
decorator           5.1.0
defusedxml          0.7.1
dill                0.3.4
entrypoints         0.3
fonttools           4.28.5
idna                3.3
importlib-metadata  4.8.2
ipykernel           6.6.0
ipython             7.30.1
ipython-genutils    0.2.0
ipywidgets          7.6.5
jedi                0.18.1
Jinja2              3.0.2
joblib              1.1.0
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      7.1.0
jupyter-console     6.4.0
jupyter-core        4.9.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
kiwisolver          1.3.2
librosa             0.8.1
llvmlite            0.37.0
MarkupSafe          2.0.1
matplotlib          3.5.1
matplotlib-inline   0.1.3
mistune             0.8.4
mkl-fft             1.3.1
mkl-random          1.2.2
mkl-service         2.4.0
multiprocess        0.70.12.2
nbclient            0.5.3
nbconvert           6.1.0
nbformat            5.1.3
nest-asyncio        1.5.4
notebook            6.4.6
numba               0.54.1
numpy               1.20.3
olefile             0.46
packaging           21.3
pandas              1.3.5
pandocfilters       1.4.3
parso               0.8.3
pickleshare         0.7.5
Pillow              8.4.0
pip                 21.2.2
pooch               1.5.2
prometheus-client   0.12.0
prompt-toolkit      3.0.24
pycparser           2.21
Pygments            2.10.0
pyparsing           3.0.4
pyrsistent          0.18.0
python-dateutil     2.8.2
pytz                2021.3
pywin32             303
pywinpty            0.5.7
pyzmq               22.3.0
qtconsole           5.1.1
QtPy                1.10.0
requests            2.26.0
resampy             0.2.2
scikit-learn        1.0.2
scipy               1.7.3
seaborn             0.11.2
Send2Trash          1.8.0
setuptools          58.0.4
sip                 4.19.13
six                 1.16.0
SoundFile           0.10.3.post1
terminado           0.9.4
testpath            0.5.0
threadpoolctl       3.0.0
torch               1.10.1+cu102
torchaudio          0.10.1+cu102
torchvision         0.11.2+cu102
tornado             6.1
tqdm                4.62.3
traitlets           5.1.1
typing-extensions   3.10.0.2
urllib3             1.26.7
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.37.0
widgetsnbextension  3.5.1
wincertstore        0.2
zipp                3.6.0

**Comment by Lanther1** [comment]
![QQ截图20211218160046](https://user-images.githubusercontent.com/75920505/147872502-256d5cbd-5408-441b-9cd3-3f3c67747232.png)

**Comment by ShaheenPerveen** [comment]
@Lanther1 Could you please share some more context on this? Are you trying to run jupyter notebook or in the form of python script?

**Comment by ShaheenPerveen** [comment]
Hey @Lanther1 I would recommend to try to run the above code as jupyter notebook.
I am closing the issue as of now. Please reopen it if not resolved.
